#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-coderay
Version  : 1.1.1
Release  : 10
URL      : https://rubygems.org/downloads/coderay-1.1.1.gem
Source0  : https://rubygems.org/downloads/coderay-1.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-coderay-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
= CodeRay
Tired of blue'n'gray? Try the original version of this documentation on
coderay.rubychan.de[http://coderay.rubychan.de/doc/] :-)

%package bin
Summary: bin components for the rubygem-coderay package.
Group: Binaries

%description bin
bin components for the rubygem-coderay package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n coderay-1.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-coderay.gemspec

%build
gem build rubygem-coderay.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
coderay-1.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/coderay-1.1.0 && ruby -I.:lib:test test/functional/examples.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/coderay-1.1.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/README_INDEX.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/bin/coderay
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/duo.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/comment_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/count.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/debug_lint.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/div.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/encoder.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/html/css.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/html/numbering.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/html/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/lines_of_code.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/lint.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/null.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/page.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/span.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/statistic.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/terminal.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/token_kind_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/encoders/yaml.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/for_redcloth.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/helpers/file_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/helpers/plugin.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/helpers/plugin_host.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/helpers/word_list.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/c.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/clojure.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/cpp.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/css.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/delphi.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/diff.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/erb.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/go.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/groovy.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/haml.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/html.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/java.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/java/builtin_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/java_script.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/lua.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/php.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/python.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/raydebug.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/ruby/patterns.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/ruby/string_state.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/sass.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/sql.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/taskpaper.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/scanners/yaml.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/styles.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/styles/_map.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/styles/alpha.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/styles/style.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/token_kinds.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/tokens.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/tokens_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/lib/coderay/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/test/functional/basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/test/functional/examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/test/functional/for_redcloth.rb
/usr/lib64/ruby/gems/2.3.0/gems/coderay-1.1.1/test/functional/suite.rb
/usr/lib64/ruby/gems/2.3.0/specifications/coderay-1.1.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/coderay
